version: '3.7'

services:
  symfony:
    build: ./api/astroSheesh
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/todos?serverVersion=16.2&charset=utf8"
    volumes:
      - .:/var/www/symfony
    networks:
      - symfony-network
    
  nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - .:/var/www/symfony
      depends_on:
        - symfony
      networks:
        - symfony-network
      

networks:
  symfony-network:
    external: true

      
