version: '3.7'

services:
  db:
    build: ./db
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony-network

  adminer:
    build: ./adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - symfony-network

volumes:
  pgdata:

networks:
  symfony-network:
    external: true
